title: 'Tecnología 4º ESO'
subtitle: 'Apuntes del Profesor Carlos Barreda Falciano'
theme: jekyll-theme-midnight
light: false
description: 'Apuntes de Tecnologia'
acronym: T4ESO
exclude: [ '_drafts/2021/', '_drafts/2020' ]
baseurl:  # '/introduccion'
#url: https://ull-mfp-aet-2223.github.io/ull-mfp-aet-2223.github.io
guia_docente: 
show_downloads: false
calendario_academico: 
horarios_examenes: 
calendario_examenes: 
horarios_tutorias: 
# google_plus: https://plus.google.com/u/1/communities/101901734024125937720
organization: 
  url: https://github.com/ull-mfp-aet-2324-alu0100596113
  name: ULL-MFP-AET-2324
  master: https://campusdoctoradoyposgrado2324.ull.es/my/
profesor: https://github.com/alu0100596113
profesor_github: alu0100596113
chat: https://chat.google.com
future: true
dsi:
  apuntes: https://ull-esit-dsi-1819.github.io/dsi-1819/
sytws:
  url: https://ull-mii-sytws-1920.github.io/
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: "https://classroom.github.com/classrooms"
  name: ULL-MFP-AET-2324
collections:
  tareas:
    output: true
temas:
# - title: 'Introducción al Desarrollo Colaborativo de Proyectos en la Nube'
#    url: '/tema0-introduccion/'
#    hover: 'introduccion'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con GitHub Education'
#  url: '/tema1-github-education'
#  hover: 'github-education'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con Google'
#  url: /tema2-google-app-scripts
#  hover: 'google-app-scripts' 
plugins:
  - jemoji

